defaults:
  - model: conv_next

inference:
  batch_size: 32
  model_weights: C:\Users\User\PycharmProjects\ARISE\checkpoints\classification\model_epoch_13_jsn_accuracy_0.6762999106255023_erosion_accuracy_0.4525482219550094.pth
  bbox_csv: C:\Users\User\PycharmProjects\ARISE\data\eval_boxes\bbox_txts\all_bboxes.txt
  image_dir: C:\Users\User\PycharmProjects\ARISE\data\croped_eval
  output_csv: C:\Users\User\PycharmProjects\ARISE\submit.csv
  device: "cuda:0"